application: q-paper-generator
version: 2
runtime: python
api_version: 1

handlers:
- url: /tinymce
  static_dir: tinymce
  
- url : /(GetSingleUseKey|GetSessionKey|GetSpreadSheetList|GetWorksheetList|PrintWorkSheet|worksheet)
  script: python/spreadsheet.py
  login : admin
  
- url: /step1
  script: python/docs.py
  login: admin

- url: /step2
  script: python/docs.py
  login: admin

- url: /.*
  script: python/views.py
  login: admin
  

  


